#!/usr/bin/perl -w
#
#  Submit our pre-cooked bodies to the server on the local-host
#

use strict;
use warnings;


use LWP::UserAgent;



#
#  Send the given file
#
sub send_file_via_post
{
    my ( $file, $url ) = (@_);


    my $ua = LWP::UserAgent->new;
    my $req = HTTP::Request->new( POST => $url );

    # Read the file
    my $text = "";
    open( my $handle, "<", $file ) or die "Faild to read $file - $!";
    while ( my $line = <$handle> )
    {
        $text .= $line;
    }
    close($handle);

    $req->content($text);

    my $resp = $ua->request($req);
    if ( $resp->is_success )
    {
        my $message = $resp->decoded_content;
        print "Received reply: $message\n";
    }
    else
    {
        print "HTTP POST error code: ",    $resp->code,    "\n";
        print "HTTP POST error message: ", $resp->message, "\n";
    }
}

#
#  Get the submission URL - if specified.
#
my $url = shift || "http://localhost:9898/root/";

foreach my $file ( sort( glob("data/*.txt") ) )
{
    send_file_via_post( $file, $url );
}



