#!/bin/sh
#
#  Automatically attempt to create a test which ensures all the modules
# used in the code are availabe.
#
#

cat <<EOF
#!/usr/bin/perl -I/srv/current/common/ -I.
#
#  Test that all the Perl modules we require are available.
#
#  This list is automatically generated by modules.sh
#

use Test::More qw( no_plan );

use strict;
use warnings;

EOF


for i in `rgrep '^use ' . | grep -v 5.00 | grep -v namespace | grep -v Mojo| grep -v overload | awk '{print $2}' | tr -d \;\(\) | sort | uniq`; \
    do \
     echo "BEGIN{ use_ok( '$i' ); }"; \
     echo "require_ok( '$i' );" ; \

done

