#!/usr/bin/perl -I/srv/current/common/ -I.
#
#  Test that all the Perl modules we require are available.
#
#  This list is automatically generated by modules.sh
#

use Test::More qw( no_plan );

use strict;
use warnings;

BEGIN {use_ok('HTML::Entities');}
require_ok('HTML::Entities');
BEGIN {use_ok('JSON');}
require_ok('JSON');
BEGIN {use_ok('LWP::UserAgent');}
require_ok('LWP::UserAgent');
BEGIN {use_ok('Module::Pluggable');}
require_ok('Module::Pluggable');
BEGIN {use_ok('strict');}
require_ok('strict');
BEGIN {use_ok('Test::More');}
require_ok('Test::More');
BEGIN {use_ok('URI');}
require_ok('URI');
BEGIN {use_ok('URI::Encode');}
require_ok('URI::Encode');
BEGIN {use_ok('UUID::Tiny');}
require_ok('UUID::Tiny');
BEGIN {use_ok('warnings');}
require_ok('warnings');
BEGIN {use_ok('WebHook::Receiver');}
require_ok('WebHook::Receiver');
